### ISSUE TITLE
Repsitory interface

### ISSUE THREAD

**Issue by omosur** [Hitesh031194/ports_processor#1]
- repository interface in the same place where implementation, please move it to correct place
 - method `UpsertPort` has tblName argument, it is exposing how it is implemented (what if we not use classic db)

**Comment by Hitesh031194** [comment]
I will address both the concerns and notify.

**Comment by Hitesh031194** [comment]
> * repository interface in the same place where implementation, please move it to correct place
> * method `UpsertPort` has tblName argument, it is exposing how it is implemented (what if we not use classic db)

I have addressed both these pointers in my latest commit. Please let me know if you agree.

**Comment by omosur** [comment]
- `repository interface in the same place where implementation` - interface still present in the same package with implementation, but the caller of this functionality should say which interface should be there, not the implementer, in current implementation high-level module dependend on the low-level module, does it make sense?
 - `method UpsertPort has tblName argument` - all good here, thanks

**Comment by Hitesh031194** [comment]
> * `repository interface in the same place where implementation` - interface still present in the same package with implementation, but the caller of this functionality should say which interface should be there, not the implementer, in current implementation high-level module dependend on the low-level module, does it make sense?
> * `method UpsertPort has tblName argument` - all good here, thanks

I believe this depends on developers' POV. From my perspective repository (implementer) exposes the contract and app (caller) uses the contract. If any other component (say PortService) in future wants to use the PortRepository, PortService knows what PortRepository does from its contract. In your suggestion, if PortService wants to use the same implementation then the interface will have to be duplicated in 2 different places as now there would be 2 different callers.
